name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: 
  IMAGE_TAGS: latest 
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: 
  USERNAME: 
  PASSWORD: 

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: 
          tags: 
          containerfiles: |
            ./Dockerfile

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: 
          password: 
          registry: /

      - name: Push To Quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: NaN
          tags: NaN
          registry: /
